server:
  port: 8080
  context-path: /consumer

spring:
  datasource: # Database properties
    url: jdbc:h2:./.tmp/msgdb
    username: sa
    password:
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: create-drop

message:
  queue:
    host: 192.168.56.105
    names: DEV.MESSAGE.QUEUE.APP1
    username: guest
    password: guest
    recoveryInterval: 30000
    receiveTimeout: 1000
