server:
  port: 8080
  context-path: /consumer

spring:
  datasource: # Database properties
    url: jdbc:h2:./.tmp/msgdb
    username: sa
    password:
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: create-drop

rabbitmq:
  uri: amqp://guest:guest@192.168.56.105:5672
  queueNames: DEV.MESSAGE.QUEUE.APP1
  recoveryInterval: 10000
  receiveTimeout: 1000

