server:
  port: 8080
  context-path: /messages

spring:
  datasource: # Database properties
    url: jdbc:h2:./.tmp/cagisterdb
    username: sa
    password:
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: create-drop

message:
  queue:
    host: 192.168.99.100
    name: DEV.MESSAGE.ADD
