/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '9/27/16 6:45 PM' with Gradle 2.14
 *
 * @author sqlin, @date 9/27/16 6:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
